[package]
name = "spookfox-native"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrome_native_messaging = "0.2.0"
serde = "1.0.133"
serde_json = "1.0.74"
